import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "../../components/SessionProvider";
import NavMenu from "../../components/NavMenu";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { Locale } from "@/i18n.config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Messagelizer",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: { children: React.ReactNode; params: { lang: Locale } }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang={params.lang}>
      <body className={inter.className + " dark"}>
        <SessionProvider session={session}>
          <main className="mx-auto max-w-screen-2xl text-2xl flex gap-12 p-20">
            <NavMenu lang={params.lang} />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
